# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STRServiceExample' do
  use_frameworks!

pod 'STRService',:git => 'https://github.com/QuyenNguyenThe/STRService'
pod 'ObjectMapper'
  target 'STRServiceExampleTests' do
    inherit! :search_paths
    
  end

end
