# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleSTRService' do

  use_frameworks!
pod 'STRService', :git=>'https://github.com/QuyenNguyenThe/STRService'
  
  target 'ExampleSTRServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
